name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build assembler & processor
        run: make
        
      - name: Store executables
        uses: actions/upload-artifact@v4
        with:
          name: stored_asm
          path: |
            assembler
            processor
          if-no-files-found: error
